title: The code lounge 🍸
author: Shane Lamb
email: shanelamb1@gmail.com
description: Dev blog of software tinkerer based in Brisbane, Australia
baseurl: "" # the subpath of your site, e.g. /blog
url: https://shane-lamb.github.io
github_username:  shane-lamb
linkedin_username: shanela
paginate: 6
rss: RSS

collections:
  - projects

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
